/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AnnotationRestApiGetListUser} from './AnnotationRestApiGetListUser';
import {AnnotationRestApiGetListUser1} from './AnnotationRestApiGetListUser1';

/**
 * The AnnotationRestApiGetList model module.
 * @module model/AnnotationRestApiGetList
 * @version v1
 */
export class AnnotationRestApiGetList {
  /**
   * Constructs a new <code>AnnotationRestApiGetList</code>.
   * @alias module:model/AnnotationRestApiGetList
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AnnotationRestApiGetList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnnotationRestApiGetList} obj Optional instance to populate.
   * @return {module:model/AnnotationRestApiGetList} The populated <code>AnnotationRestApiGetList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnnotationRestApiGetList();
      if (data.hasOwnProperty('changed_by'))
        obj.changedBy = AnnotationRestApiGetListUser.constructFromObject(data['changed_by']);
      if (data.hasOwnProperty('changed_on_delta_humanized'))
        obj.changedOnDeltaHumanized = ApiClient.convertToType(data['changed_on_delta_humanized'], Object);
      if (data.hasOwnProperty('created_by'))
        obj.createdBy = AnnotationRestApiGetListUser1.constructFromObject(data['created_by']);
      if (data.hasOwnProperty('end_dttm'))
        obj.endDttm = ApiClient.convertToType(data['end_dttm'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('long_descr'))
        obj.longDescr = ApiClient.convertToType(data['long_descr'], 'String');
      if (data.hasOwnProperty('short_descr'))
        obj.shortDescr = ApiClient.convertToType(data['short_descr'], 'String');
      if (data.hasOwnProperty('start_dttm'))
        obj.startDttm = ApiClient.convertToType(data['start_dttm'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {module:model/AnnotationRestApiGetListUser} changedBy
 */
AnnotationRestApiGetList.prototype.changedBy = undefined;

/**
 * @member {Object} changedOnDeltaHumanized
 */
AnnotationRestApiGetList.prototype.changedOnDeltaHumanized = undefined;

/**
 * @member {module:model/AnnotationRestApiGetListUser1} createdBy
 */
AnnotationRestApiGetList.prototype.createdBy = undefined;

/**
 * @member {Date} endDttm
 */
AnnotationRestApiGetList.prototype.endDttm = undefined;

/**
 * @member {Number} id
 */
AnnotationRestApiGetList.prototype.id = undefined;

/**
 * @member {String} longDescr
 */
AnnotationRestApiGetList.prototype.longDescr = undefined;

/**
 * @member {String} shortDescr
 */
AnnotationRestApiGetList.prototype.shortDescr = undefined;

/**
 * @member {Date} startDttm
 */
AnnotationRestApiGetList.prototype.startDttm = undefined;

