/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AvailableDomainsSchema model module.
 * @module model/AvailableDomainsSchema
 * @version v1
 */
export class AvailableDomainsSchema {
  /**
   * Constructs a new <code>AvailableDomainsSchema</code>.
   * @alias module:model/AvailableDomainsSchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AvailableDomainsSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AvailableDomainsSchema} obj Optional instance to populate.
   * @return {module:model/AvailableDomainsSchema} The populated <code>AvailableDomainsSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AvailableDomainsSchema();
      if (data.hasOwnProperty('domains'))
        obj.domains = ApiClient.convertToType(data['domains'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} domains
 */
AvailableDomainsSchema.prototype.domains = undefined;

