/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ChartCacheScreenshotResponseSchema model module.
 * @module model/ChartCacheScreenshotResponseSchema
 * @version v1
 */
export class ChartCacheScreenshotResponseSchema {
  /**
   * Constructs a new <code>ChartCacheScreenshotResponseSchema</code>.
   * @alias module:model/ChartCacheScreenshotResponseSchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChartCacheScreenshotResponseSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChartCacheScreenshotResponseSchema} obj Optional instance to populate.
   * @return {module:model/ChartCacheScreenshotResponseSchema} The populated <code>ChartCacheScreenshotResponseSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChartCacheScreenshotResponseSchema();
      if (data.hasOwnProperty('cache_key'))
        obj.cacheKey = ApiClient.convertToType(data['cache_key'], 'String');
      if (data.hasOwnProperty('chart_url'))
        obj.chartUrl = ApiClient.convertToType(data['chart_url'], 'String');
      if (data.hasOwnProperty('image_url'))
        obj.imageUrl = ApiClient.convertToType(data['image_url'], 'String');
    }
    return obj;
  }
}

/**
 * The cache key
 * @member {String} cacheKey
 */
ChartCacheScreenshotResponseSchema.prototype.cacheKey = undefined;

/**
 * The url to render the chart
 * @member {String} chartUrl
 */
ChartCacheScreenshotResponseSchema.prototype.chartUrl = undefined;

/**
 * The url to fetch the screenshot
 * @member {String} imageUrl
 */
ChartCacheScreenshotResponseSchema.prototype.imageUrl = undefined;

