/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ChartDataResponseResult} from './ChartDataResponseResult';

/**
 * The ChartDataResponseSchema model module.
 * @module model/ChartDataResponseSchema
 * @version v1
 */
export class ChartDataResponseSchema {
  /**
   * Constructs a new <code>ChartDataResponseSchema</code>.
   * @alias module:model/ChartDataResponseSchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChartDataResponseSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChartDataResponseSchema} obj Optional instance to populate.
   * @return {module:model/ChartDataResponseSchema} The populated <code>ChartDataResponseSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChartDataResponseSchema();
      if (data.hasOwnProperty('result'))
        obj.result = ApiClient.convertToType(data['result'], [ChartDataResponseResult]);
    }
    return obj;
  }
}

/**
 * A list of results for each corresponding query in the request.
 * @member {Array.<module:model/ChartDataResponseResult>} result
 */
ChartDataResponseSchema.prototype.result = undefined;

