/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CssTemplateRestApiGetListUser} from './CssTemplateRestApiGetListUser';
import {CssTemplateRestApiGetListUser1} from './CssTemplateRestApiGetListUser1';

/**
 * The CssTemplateRestApiGetList model module.
 * @module model/CssTemplateRestApiGetList
 * @version v1
 */
export class CssTemplateRestApiGetList {
  /**
   * Constructs a new <code>CssTemplateRestApiGetList</code>.
   * @alias module:model/CssTemplateRestApiGetList
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CssTemplateRestApiGetList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CssTemplateRestApiGetList} obj Optional instance to populate.
   * @return {module:model/CssTemplateRestApiGetList} The populated <code>CssTemplateRestApiGetList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CssTemplateRestApiGetList();
      if (data.hasOwnProperty('changed_by'))
        obj.changedBy = CssTemplateRestApiGetListUser.constructFromObject(data['changed_by']);
      if (data.hasOwnProperty('changed_on_delta_humanized'))
        obj.changedOnDeltaHumanized = ApiClient.convertToType(data['changed_on_delta_humanized'], Object);
      if (data.hasOwnProperty('created_by'))
        obj.createdBy = CssTemplateRestApiGetListUser1.constructFromObject(data['created_by']);
      if (data.hasOwnProperty('created_on'))
        obj.createdOn = ApiClient.convertToType(data['created_on'], 'Date');
      if (data.hasOwnProperty('css'))
        obj.css = ApiClient.convertToType(data['css'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('template_name'))
        obj.templateName = ApiClient.convertToType(data['template_name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/CssTemplateRestApiGetListUser} changedBy
 */
CssTemplateRestApiGetList.prototype.changedBy = undefined;

/**
 * @member {Object} changedOnDeltaHumanized
 */
CssTemplateRestApiGetList.prototype.changedOnDeltaHumanized = undefined;

/**
 * @member {module:model/CssTemplateRestApiGetListUser1} createdBy
 */
CssTemplateRestApiGetList.prototype.createdBy = undefined;

/**
 * @member {Date} createdOn
 */
CssTemplateRestApiGetList.prototype.createdOn = undefined;

/**
 * @member {String} css
 */
CssTemplateRestApiGetList.prototype.css = undefined;

/**
 * @member {Number} id
 */
CssTemplateRestApiGetList.prototype.id = undefined;

/**
 * @member {String} templateName
 */
CssTemplateRestApiGetList.prototype.templateName = undefined;

