/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DatasetRestApiGetDatabase} from './DatasetRestApiGetDatabase';
import {DatasetRestApiGetSqlMetric} from './DatasetRestApiGetSqlMetric';
import {DatasetRestApiGetTableColumn} from './DatasetRestApiGetTableColumn';
import {DatasetRestApiGetUser} from './DatasetRestApiGetUser';
import {DatasetRestApiGetUser1} from './DatasetRestApiGetUser1';
import {DatasetRestApiGetUser2} from './DatasetRestApiGetUser2';

/**
 * The DatasetRestApiGet model module.
 * @module model/DatasetRestApiGet
 * @version v1
 */
export class DatasetRestApiGet {
  /**
   * Constructs a new <code>DatasetRestApiGet</code>.
   * @alias module:model/DatasetRestApiGet
   * @class
   * @param columns {module:model/DatasetRestApiGetTableColumn} 
   * @param database {module:model/DatasetRestApiGetDatabase} 
   * @param metrics {module:model/DatasetRestApiGetSqlMetric} 
   * @param tableName {String} 
   */
  constructor(columns, database, metrics, tableName) {
    this.columns = columns;
    this.database = database;
    this.metrics = metrics;
    this.tableName = tableName;
  }

  /**
   * Constructs a <code>DatasetRestApiGet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DatasetRestApiGet} obj Optional instance to populate.
   * @return {module:model/DatasetRestApiGet} The populated <code>DatasetRestApiGet</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DatasetRestApiGet();
      if (data.hasOwnProperty('cache_timeout'))
        obj.cacheTimeout = ApiClient.convertToType(data['cache_timeout'], 'Number');
      if (data.hasOwnProperty('changed_by'))
        obj.changedBy = DatasetRestApiGetUser.constructFromObject(data['changed_by']);
      if (data.hasOwnProperty('changed_on'))
        obj.changedOn = ApiClient.convertToType(data['changed_on'], 'Date');
      if (data.hasOwnProperty('changed_on_humanized'))
        obj.changedOnHumanized = ApiClient.convertToType(data['changed_on_humanized'], Object);
      if (data.hasOwnProperty('column_formats'))
        obj.columnFormats = ApiClient.convertToType(data['column_formats'], Object);
      if (data.hasOwnProperty('columns'))
        obj.columns = DatasetRestApiGetTableColumn.constructFromObject(data['columns']);
      if (data.hasOwnProperty('created_by'))
        obj.createdBy = DatasetRestApiGetUser2.constructFromObject(data['created_by']);
      if (data.hasOwnProperty('created_on'))
        obj.createdOn = ApiClient.convertToType(data['created_on'], 'Date');
      if (data.hasOwnProperty('created_on_humanized'))
        obj.createdOnHumanized = ApiClient.convertToType(data['created_on_humanized'], Object);
      if (data.hasOwnProperty('database'))
        obj.database = DatasetRestApiGetDatabase.constructFromObject(data['database']);
      if (data.hasOwnProperty('datasource_name'))
        obj.datasourceName = ApiClient.convertToType(data['datasource_name'], Object);
      if (data.hasOwnProperty('datasource_type'))
        obj.datasourceType = ApiClient.convertToType(data['datasource_type'], Object);
      if (data.hasOwnProperty('default_endpoint'))
        obj.defaultEndpoint = ApiClient.convertToType(data['default_endpoint'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('extra'))
        obj.extra = ApiClient.convertToType(data['extra'], 'String');
      if (data.hasOwnProperty('fetch_values_predicate'))
        obj.fetchValuesPredicate = ApiClient.convertToType(data['fetch_values_predicate'], 'String');
      if (data.hasOwnProperty('filter_select_enabled'))
        obj.filterSelectEnabled = ApiClient.convertToType(data['filter_select_enabled'], 'Boolean');
      if (data.hasOwnProperty('granularity_sqla'))
        obj.granularitySqla = ApiClient.convertToType(data['granularity_sqla'], Object);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('is_managed_externally'))
        obj.isManagedExternally = ApiClient.convertToType(data['is_managed_externally'], 'Boolean');
      if (data.hasOwnProperty('is_sqllab_view'))
        obj.isSqllabView = ApiClient.convertToType(data['is_sqllab_view'], 'Boolean');
      if (data.hasOwnProperty('kind'))
        obj.kind = ApiClient.convertToType(data['kind'], Object);
      if (data.hasOwnProperty('main_dttm_col'))
        obj.mainDttmCol = ApiClient.convertToType(data['main_dttm_col'], 'String');
      if (data.hasOwnProperty('metrics'))
        obj.metrics = DatasetRestApiGetSqlMetric.constructFromObject(data['metrics']);
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], Object);
      if (data.hasOwnProperty('offset'))
        obj.offset = ApiClient.convertToType(data['offset'], 'Number');
      if (data.hasOwnProperty('order_by_choices'))
        obj.orderByChoices = ApiClient.convertToType(data['order_by_choices'], Object);
      if (data.hasOwnProperty('owners'))
        obj.owners = DatasetRestApiGetUser1.constructFromObject(data['owners']);
      if (data.hasOwnProperty('schema'))
        obj.schema = ApiClient.convertToType(data['schema'], 'String');
      if (data.hasOwnProperty('select_star'))
        obj.selectStar = ApiClient.convertToType(data['select_star'], Object);
      if (data.hasOwnProperty('sql'))
        obj.sql = ApiClient.convertToType(data['sql'], 'String');
      if (data.hasOwnProperty('table_name'))
        obj.tableName = ApiClient.convertToType(data['table_name'], 'String');
      if (data.hasOwnProperty('template_params'))
        obj.templateParams = ApiClient.convertToType(data['template_params'], 'String');
      if (data.hasOwnProperty('time_grain_sqla'))
        obj.timeGrainSqla = ApiClient.convertToType(data['time_grain_sqla'], Object);
      if (data.hasOwnProperty('uid'))
        obj.uid = ApiClient.convertToType(data['uid'], Object);
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], Object);
      if (data.hasOwnProperty('verbose_map'))
        obj.verboseMap = ApiClient.convertToType(data['verbose_map'], Object);
    }
    return obj;
  }
}

/**
 * @member {Number} cacheTimeout
 */
DatasetRestApiGet.prototype.cacheTimeout = undefined;

/**
 * @member {module:model/DatasetRestApiGetUser} changedBy
 */
DatasetRestApiGet.prototype.changedBy = undefined;

/**
 * @member {Date} changedOn
 */
DatasetRestApiGet.prototype.changedOn = undefined;

/**
 * @member {Object} changedOnHumanized
 */
DatasetRestApiGet.prototype.changedOnHumanized = undefined;

/**
 * @member {Object} columnFormats
 */
DatasetRestApiGet.prototype.columnFormats = undefined;

/**
 * @member {module:model/DatasetRestApiGetTableColumn} columns
 */
DatasetRestApiGet.prototype.columns = undefined;

/**
 * @member {module:model/DatasetRestApiGetUser2} createdBy
 */
DatasetRestApiGet.prototype.createdBy = undefined;

/**
 * @member {Date} createdOn
 */
DatasetRestApiGet.prototype.createdOn = undefined;

/**
 * @member {Object} createdOnHumanized
 */
DatasetRestApiGet.prototype.createdOnHumanized = undefined;

/**
 * @member {module:model/DatasetRestApiGetDatabase} database
 */
DatasetRestApiGet.prototype.database = undefined;

/**
 * @member {Object} datasourceName
 */
DatasetRestApiGet.prototype.datasourceName = undefined;

/**
 * @member {Object} datasourceType
 */
DatasetRestApiGet.prototype.datasourceType = undefined;

/**
 * @member {String} defaultEndpoint
 */
DatasetRestApiGet.prototype.defaultEndpoint = undefined;

/**
 * @member {String} description
 */
DatasetRestApiGet.prototype.description = undefined;

/**
 * @member {String} extra
 */
DatasetRestApiGet.prototype.extra = undefined;

/**
 * @member {String} fetchValuesPredicate
 */
DatasetRestApiGet.prototype.fetchValuesPredicate = undefined;

/**
 * @member {Boolean} filterSelectEnabled
 */
DatasetRestApiGet.prototype.filterSelectEnabled = undefined;

/**
 * @member {Object} granularitySqla
 */
DatasetRestApiGet.prototype.granularitySqla = undefined;

/**
 * @member {Number} id
 */
DatasetRestApiGet.prototype.id = undefined;

/**
 * @member {Boolean} isManagedExternally
 */
DatasetRestApiGet.prototype.isManagedExternally = undefined;

/**
 * @member {Boolean} isSqllabView
 */
DatasetRestApiGet.prototype.isSqllabView = undefined;

/**
 * @member {Object} kind
 */
DatasetRestApiGet.prototype.kind = undefined;

/**
 * @member {String} mainDttmCol
 */
DatasetRestApiGet.prototype.mainDttmCol = undefined;

/**
 * @member {module:model/DatasetRestApiGetSqlMetric} metrics
 */
DatasetRestApiGet.prototype.metrics = undefined;

/**
 * @member {Object} name
 */
DatasetRestApiGet.prototype.name = undefined;

/**
 * @member {Number} offset
 */
DatasetRestApiGet.prototype.offset = undefined;

/**
 * @member {Object} orderByChoices
 */
DatasetRestApiGet.prototype.orderByChoices = undefined;

/**
 * @member {module:model/DatasetRestApiGetUser1} owners
 */
DatasetRestApiGet.prototype.owners = undefined;

/**
 * @member {String} schema
 */
DatasetRestApiGet.prototype.schema = undefined;

/**
 * @member {Object} selectStar
 */
DatasetRestApiGet.prototype.selectStar = undefined;

/**
 * @member {String} sql
 */
DatasetRestApiGet.prototype.sql = undefined;

/**
 * @member {String} tableName
 */
DatasetRestApiGet.prototype.tableName = undefined;

/**
 * @member {String} templateParams
 */
DatasetRestApiGet.prototype.templateParams = undefined;

/**
 * @member {Object} timeGrainSqla
 */
DatasetRestApiGet.prototype.timeGrainSqla = undefined;

/**
 * @member {Object} uid
 */
DatasetRestApiGet.prototype.uid = undefined;

/**
 * @member {Object} url
 */
DatasetRestApiGet.prototype.url = undefined;

/**
 * @member {Object} verboseMap
 */
DatasetRestApiGet.prototype.verboseMap = undefined;

