/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DatasetColumnsPut model module.
 * @module model/DatasetColumnsPut
 * @version v1
 */
export class DatasetColumnsPut {
  /**
   * Constructs a new <code>DatasetColumnsPut</code>.
   * @alias module:model/DatasetColumnsPut
   * @class
   * @param columnName {String} 
   */
  constructor(columnName) {
    this.columnName = columnName;
  }

  /**
   * Constructs a <code>DatasetColumnsPut</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DatasetColumnsPut} obj Optional instance to populate.
   * @return {module:model/DatasetColumnsPut} The populated <code>DatasetColumnsPut</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DatasetColumnsPut();
      if (data.hasOwnProperty('advanced_data_type'))
        obj.advancedDataType = ApiClient.convertToType(data['advanced_data_type'], 'String');
      if (data.hasOwnProperty('column_name'))
        obj.columnName = ApiClient.convertToType(data['column_name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('expression'))
        obj.expression = ApiClient.convertToType(data['expression'], 'String');
      if (data.hasOwnProperty('extra'))
        obj.extra = ApiClient.convertToType(data['extra'], 'String');
      if (data.hasOwnProperty('filterable'))
        obj.filterable = ApiClient.convertToType(data['filterable'], 'Boolean');
      if (data.hasOwnProperty('groupby'))
        obj.groupby = ApiClient.convertToType(data['groupby'], 'Boolean');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('is_active'))
        obj.isActive = ApiClient.convertToType(data['is_active'], 'Boolean');
      if (data.hasOwnProperty('is_dttm'))
        obj.isDttm = ApiClient.convertToType(data['is_dttm'], 'Boolean');
      if (data.hasOwnProperty('python_date_format'))
        obj.pythonDateFormat = ApiClient.convertToType(data['python_date_format'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('uuid'))
        obj.uuid = ApiClient.convertToType(data['uuid'], 'String');
      if (data.hasOwnProperty('verbose_name'))
        obj.verboseName = ApiClient.convertToType(data['verbose_name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} advancedDataType
 */
DatasetColumnsPut.prototype.advancedDataType = undefined;

/**
 * @member {String} columnName
 */
DatasetColumnsPut.prototype.columnName = undefined;

/**
 * @member {String} description
 */
DatasetColumnsPut.prototype.description = undefined;

/**
 * @member {String} expression
 */
DatasetColumnsPut.prototype.expression = undefined;

/**
 * @member {String} extra
 */
DatasetColumnsPut.prototype.extra = undefined;

/**
 * @member {Boolean} filterable
 */
DatasetColumnsPut.prototype.filterable = undefined;

/**
 * @member {Boolean} groupby
 */
DatasetColumnsPut.prototype.groupby = undefined;

/**
 * @member {Number} id
 */
DatasetColumnsPut.prototype.id = undefined;

/**
 * @member {Boolean} isActive
 */
DatasetColumnsPut.prototype.isActive = undefined;

/**
 * @member {Boolean} isDttm
 */
DatasetColumnsPut.prototype.isDttm = undefined;

/**
 * @member {String} pythonDateFormat
 */
DatasetColumnsPut.prototype.pythonDateFormat = undefined;

/**
 * @member {String} type
 */
DatasetColumnsPut.prototype.type = undefined;

/**
 * @member {String} uuid
 */
DatasetColumnsPut.prototype.uuid = undefined;

/**
 * @member {String} verboseName
 */
DatasetColumnsPut.prototype.verboseName = undefined;

