/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DatabaseRestApiGet model module.
 * @module model/DatabaseRestApiGet
 * @version v1
 */
export class DatabaseRestApiGet {
  /**
   * Constructs a new <code>DatabaseRestApiGet</code>.
   * @alias module:model/DatabaseRestApiGet
   * @class
   * @param databaseName {String} 
   */
  constructor(databaseName) {
    this.databaseName = databaseName;
  }

  /**
   * Constructs a <code>DatabaseRestApiGet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DatabaseRestApiGet} obj Optional instance to populate.
   * @return {module:model/DatabaseRestApiGet} The populated <code>DatabaseRestApiGet</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DatabaseRestApiGet();
      if (data.hasOwnProperty('allow_ctas'))
        obj.allowCtas = ApiClient.convertToType(data['allow_ctas'], 'Boolean');
      if (data.hasOwnProperty('allow_cvas'))
        obj.allowCvas = ApiClient.convertToType(data['allow_cvas'], 'Boolean');
      if (data.hasOwnProperty('allow_dml'))
        obj.allowDml = ApiClient.convertToType(data['allow_dml'], 'Boolean');
      if (data.hasOwnProperty('allow_file_upload'))
        obj.allowFileUpload = ApiClient.convertToType(data['allow_file_upload'], 'Boolean');
      if (data.hasOwnProperty('allow_run_async'))
        obj.allowRunAsync = ApiClient.convertToType(data['allow_run_async'], 'Boolean');
      if (data.hasOwnProperty('backend'))
        obj.backend = ApiClient.convertToType(data['backend'], Object);
      if (data.hasOwnProperty('cache_timeout'))
        obj.cacheTimeout = ApiClient.convertToType(data['cache_timeout'], 'Number');
      if (data.hasOwnProperty('configuration_method'))
        obj.configurationMethod = ApiClient.convertToType(data['configuration_method'], 'String');
      if (data.hasOwnProperty('database_name'))
        obj.databaseName = ApiClient.convertToType(data['database_name'], 'String');
      if (data.hasOwnProperty('driver'))
        obj.driver = ApiClient.convertToType(data['driver'], Object);
      if (data.hasOwnProperty('engine_information'))
        obj.engineInformation = ApiClient.convertToType(data['engine_information'], Object);
      if (data.hasOwnProperty('expose_in_sqllab'))
        obj.exposeInSqllab = ApiClient.convertToType(data['expose_in_sqllab'], 'Boolean');
      if (data.hasOwnProperty('force_ctas_schema'))
        obj.forceCtasSchema = ApiClient.convertToType(data['force_ctas_schema'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('impersonate_user'))
        obj.impersonateUser = ApiClient.convertToType(data['impersonate_user'], 'Boolean');
      if (data.hasOwnProperty('is_managed_externally'))
        obj.isManagedExternally = ApiClient.convertToType(data['is_managed_externally'], 'Boolean');
      if (data.hasOwnProperty('uuid'))
        obj.uuid = ApiClient.convertToType(data['uuid'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Boolean} allowCtas
 */
DatabaseRestApiGet.prototype.allowCtas = undefined;

/**
 * @member {Boolean} allowCvas
 */
DatabaseRestApiGet.prototype.allowCvas = undefined;

/**
 * @member {Boolean} allowDml
 */
DatabaseRestApiGet.prototype.allowDml = undefined;

/**
 * @member {Boolean} allowFileUpload
 */
DatabaseRestApiGet.prototype.allowFileUpload = undefined;

/**
 * @member {Boolean} allowRunAsync
 */
DatabaseRestApiGet.prototype.allowRunAsync = undefined;

/**
 * @member {Object} backend
 */
DatabaseRestApiGet.prototype.backend = undefined;

/**
 * @member {Number} cacheTimeout
 */
DatabaseRestApiGet.prototype.cacheTimeout = undefined;

/**
 * @member {String} configurationMethod
 */
DatabaseRestApiGet.prototype.configurationMethod = undefined;

/**
 * @member {String} databaseName
 */
DatabaseRestApiGet.prototype.databaseName = undefined;

/**
 * @member {Object} driver
 */
DatabaseRestApiGet.prototype.driver = undefined;

/**
 * @member {Object} engineInformation
 */
DatabaseRestApiGet.prototype.engineInformation = undefined;

/**
 * @member {Boolean} exposeInSqllab
 */
DatabaseRestApiGet.prototype.exposeInSqllab = undefined;

/**
 * @member {String} forceCtasSchema
 */
DatabaseRestApiGet.prototype.forceCtasSchema = undefined;

/**
 * @member {Number} id
 */
DatabaseRestApiGet.prototype.id = undefined;

/**
 * @member {Boolean} impersonateUser
 */
DatabaseRestApiGet.prototype.impersonateUser = undefined;

/**
 * @member {Boolean} isManagedExternally
 */
DatabaseRestApiGet.prototype.isManagedExternally = undefined;

/**
 * @member {String} uuid
 */
DatabaseRestApiGet.prototype.uuid = undefined;

