/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DistinctResultResponse model module.
 * @module model/DistinctResultResponse
 * @version v1
 */
export class DistinctResultResponse {
  /**
   * Constructs a new <code>DistinctResultResponse</code>.
   * @alias module:model/DistinctResultResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DistinctResultResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DistinctResultResponse} obj Optional instance to populate.
   * @return {module:model/DistinctResultResponse} The populated <code>DistinctResultResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DistinctResultResponse();
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
    }
    return obj;
  }
}

/**
 * The distinct item
 * @member {String} text
 */
DistinctResultResponse.prototype.text = undefined;

