/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ExecutePayloadSchema model module.
 * @module model/ExecutePayloadSchema
 * @version v1
 */
export class ExecutePayloadSchema {
  /**
   * Constructs a new <code>ExecutePayloadSchema</code>.
   * @alias module:model/ExecutePayloadSchema
   * @class
   * @param databaseId {Number} 
   * @param sql {String} 
   */
  constructor(databaseId, sql) {
    this.databaseId = databaseId;
    this.sql = sql;
  }

  /**
   * Constructs a <code>ExecutePayloadSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExecutePayloadSchema} obj Optional instance to populate.
   * @return {module:model/ExecutePayloadSchema} The populated <code>ExecutePayloadSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExecutePayloadSchema();
      if (data.hasOwnProperty('client_id'))
        obj.clientId = ApiClient.convertToType(data['client_id'], 'String');
      if (data.hasOwnProperty('ctas_method'))
        obj.ctasMethod = ApiClient.convertToType(data['ctas_method'], 'String');
      if (data.hasOwnProperty('database_id'))
        obj.databaseId = ApiClient.convertToType(data['database_id'], 'Number');
      if (data.hasOwnProperty('expand_data'))
        obj.expandData = ApiClient.convertToType(data['expand_data'], 'Boolean');
      if (data.hasOwnProperty('json'))
        obj.json = ApiClient.convertToType(data['json'], 'Boolean');
      if (data.hasOwnProperty('queryLimit'))
        obj.queryLimit = ApiClient.convertToType(data['queryLimit'], 'Number');
      if (data.hasOwnProperty('runAsync'))
        obj.runAsync = ApiClient.convertToType(data['runAsync'], 'Boolean');
      if (data.hasOwnProperty('schema'))
        obj.schema = ApiClient.convertToType(data['schema'], 'String');
      if (data.hasOwnProperty('select_as_cta'))
        obj.selectAsCta = ApiClient.convertToType(data['select_as_cta'], 'Boolean');
      if (data.hasOwnProperty('sql'))
        obj.sql = ApiClient.convertToType(data['sql'], 'String');
      if (data.hasOwnProperty('sql_editor_id'))
        obj.sqlEditorId = ApiClient.convertToType(data['sql_editor_id'], 'String');
      if (data.hasOwnProperty('tab'))
        obj.tab = ApiClient.convertToType(data['tab'], 'String');
      if (data.hasOwnProperty('templateParams'))
        obj.templateParams = ApiClient.convertToType(data['templateParams'], 'String');
      if (data.hasOwnProperty('tmp_table_name'))
        obj.tmpTableName = ApiClient.convertToType(data['tmp_table_name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} clientId
 */
ExecutePayloadSchema.prototype.clientId = undefined;

/**
 * @member {String} ctasMethod
 */
ExecutePayloadSchema.prototype.ctasMethod = undefined;

/**
 * @member {Number} databaseId
 */
ExecutePayloadSchema.prototype.databaseId = undefined;

/**
 * @member {Boolean} expandData
 */
ExecutePayloadSchema.prototype.expandData = undefined;

/**
 * @member {Boolean} json
 */
ExecutePayloadSchema.prototype.json = undefined;

/**
 * @member {Number} queryLimit
 */
ExecutePayloadSchema.prototype.queryLimit = undefined;

/**
 * @member {Boolean} runAsync
 */
ExecutePayloadSchema.prototype.runAsync = undefined;

/**
 * @member {String} schema
 */
ExecutePayloadSchema.prototype.schema = undefined;

/**
 * @member {Boolean} selectAsCta
 */
ExecutePayloadSchema.prototype.selectAsCta = undefined;

/**
 * @member {String} sql
 */
ExecutePayloadSchema.prototype.sql = undefined;

/**
 * @member {String} sqlEditorId
 */
ExecutePayloadSchema.prototype.sqlEditorId = undefined;

/**
 * @member {String} tab
 */
ExecutePayloadSchema.prototype.tab = undefined;

/**
 * @member {String} templateParams
 */
ExecutePayloadSchema.prototype.templateParams = undefined;

/**
 * @member {String} tmpTableName
 */
ExecutePayloadSchema.prototype.tmpTableName = undefined;

