/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetDeleteIdsSchema model module.
 * @module model/GetDeleteIdsSchema
 * @version v1
 */
export class GetDeleteIdsSchema extends Array {
  /**
   * Constructs a new <code>GetDeleteIdsSchema</code>.
   * @alias module:model/GetDeleteIdsSchema
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>GetDeleteIdsSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetDeleteIdsSchema} obj Optional instance to populate.
   * @return {module:model/GetDeleteIdsSchema} The populated <code>GetDeleteIdsSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetDeleteIdsSchema();
      ApiClient.constructFromObject(data, obj, 'Number');
    }
    return obj;
  }
}
