/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetRecentActivitySchema model module.
 * @module model/GetRecentActivitySchema
 * @version v1
 */
export class GetRecentActivitySchema {
  /**
   * Constructs a new <code>GetRecentActivitySchema</code>.
   * @alias module:model/GetRecentActivitySchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetRecentActivitySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetRecentActivitySchema} obj Optional instance to populate.
   * @return {module:model/GetRecentActivitySchema} The populated <code>GetRecentActivitySchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetRecentActivitySchema();
      if (data.hasOwnProperty('actions'))
        obj.actions = ApiClient.convertToType(data['actions'], ['String']);
      if (data.hasOwnProperty('distinct'))
        obj.distinct = ApiClient.convertToType(data['distinct'], 'Boolean');
      if (data.hasOwnProperty('page'))
        obj.page = ApiClient.convertToType(data['page'], 'Number');
      if (data.hasOwnProperty('page_size'))
        obj.pageSize = ApiClient.convertToType(data['page_size'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} actions
 */
GetRecentActivitySchema.prototype.actions = undefined;

/**
 * @member {Boolean} distinct
 */
GetRecentActivitySchema.prototype.distinct = undefined;

/**
 * @member {Number} page
 */
GetRecentActivitySchema.prototype.page = undefined;

/**
 * @member {Number} pageSize
 */
GetRecentActivitySchema.prototype.pageSize = undefined;

