/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TaggedObjectEntityResponseSchema} from './TaggedObjectEntityResponseSchema';

/**
 * The InlineResponse20063 model module.
 * @module model/InlineResponse20063
 * @version v1
 */
export class InlineResponse20063 {
  /**
   * Constructs a new <code>InlineResponse20063</code>.
   * @alias module:model/InlineResponse20063
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20063</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20063} obj Optional instance to populate.
   * @return {module:model/InlineResponse20063} The populated <code>InlineResponse20063</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20063();
      if (data.hasOwnProperty('result'))
        obj.result = ApiClient.convertToType(data['result'], [TaggedObjectEntityResponseSchema]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/TaggedObjectEntityResponseSchema>} result
 */
InlineResponse20063.prototype.result = undefined;

