/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse2002FiltersColumnName} from './InlineResponse2002FiltersColumnName';

/**
 * The InlineResponse2002Filters model module.
 * @module model/InlineResponse2002Filters
 * @version v1
 */
export class InlineResponse2002Filters {
  /**
   * Constructs a new <code>InlineResponse2002Filters</code>.
   * @alias module:model/InlineResponse2002Filters
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2002Filters</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2002Filters} obj Optional instance to populate.
   * @return {module:model/InlineResponse2002Filters} The populated <code>InlineResponse2002Filters</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2002Filters();
      if (data.hasOwnProperty('column_name'))
        obj.columnName = ApiClient.convertToType(data['column_name'], [InlineResponse2002FiltersColumnName]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/InlineResponse2002FiltersColumnName>} columnName
 */
InlineResponse2002Filters.prototype.columnName = undefined;

