/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LogRestApiPut model module.
 * @module model/LogRestApiPut
 * @version v1
 */
export class LogRestApiPut {
  /**
   * Constructs a new <code>LogRestApiPut</code>.
   * @alias module:model/LogRestApiPut
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LogRestApiPut</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LogRestApiPut} obj Optional instance to populate.
   * @return {module:model/LogRestApiPut} The populated <code>LogRestApiPut</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LogRestApiPut();
      if (data.hasOwnProperty('action'))
        obj.action = ApiClient.convertToType(data['action'], 'String');
      if (data.hasOwnProperty('dttm'))
        obj.dttm = ApiClient.convertToType(data['dttm'], 'Date');
      if (data.hasOwnProperty('json'))
        obj.json = ApiClient.convertToType(data['json'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = ApiClient.convertToType(data['user'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} action
 */
LogRestApiPut.prototype.action = undefined;

/**
 * @member {Date} dttm
 */
LogRestApiPut.prototype.dttm = undefined;

/**
 * @member {String} json
 */
LogRestApiPut.prototype.json = undefined;

/**
 * @member {Object} user
 */
LogRestApiPut.prototype.user = undefined;

