/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The QueriesGetUpdatedSinceSchema model module.
 * @module model/QueriesGetUpdatedSinceSchema
 * @version v1
 */
export class QueriesGetUpdatedSinceSchema {
  /**
   * Constructs a new <code>QueriesGetUpdatedSinceSchema</code>.
   * @alias module:model/QueriesGetUpdatedSinceSchema
   * @class
   * @param lastUpdatedMs {Number} 
   */
  constructor(lastUpdatedMs) {
    this.lastUpdatedMs = lastUpdatedMs;
  }

  /**
   * Constructs a <code>QueriesGetUpdatedSinceSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QueriesGetUpdatedSinceSchema} obj Optional instance to populate.
   * @return {module:model/QueriesGetUpdatedSinceSchema} The populated <code>QueriesGetUpdatedSinceSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new QueriesGetUpdatedSinceSchema();
      if (data.hasOwnProperty('last_updated_ms'))
        obj.lastUpdatedMs = ApiClient.convertToType(data['last_updated_ms'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} lastUpdatedMs
 */
QueriesGetUpdatedSinceSchema.prototype.lastUpdatedMs = undefined;

