/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RelatedResultResponse model module.
 * @module model/RelatedResultResponse
 * @version v1
 */
export class RelatedResultResponse {
  /**
   * Constructs a new <code>RelatedResultResponse</code>.
   * @alias module:model/RelatedResultResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RelatedResultResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RelatedResultResponse} obj Optional instance to populate.
   * @return {module:model/RelatedResultResponse} The populated <code>RelatedResultResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RelatedResultResponse();
      if (data.hasOwnProperty('extra'))
        obj.extra = ApiClient.convertToType(data['extra'], Object);
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
    }
    return obj;
  }
}

/**
 * The extra metadata for related item
 * @member {Object} extra
 */
RelatedResultResponse.prototype.extra = undefined;

/**
 * The related item string representation
 * @member {String} text
 */
RelatedResultResponse.prototype.text = undefined;

/**
 * The related item identifier
 * @member {Number} value
 */
RelatedResultResponse.prototype.value = undefined;

