/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {RelatedResultResponse} from './RelatedResultResponse';

/**
 * The RelatedResponseSchema model module.
 * @module model/RelatedResponseSchema
 * @version v1
 */
export class RelatedResponseSchema {
  /**
   * Constructs a new <code>RelatedResponseSchema</code>.
   * @alias module:model/RelatedResponseSchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RelatedResponseSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RelatedResponseSchema} obj Optional instance to populate.
   * @return {module:model/RelatedResponseSchema} The populated <code>RelatedResponseSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RelatedResponseSchema();
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Number');
      if (data.hasOwnProperty('result'))
        obj.result = ApiClient.convertToType(data['result'], [RelatedResultResponse]);
    }
    return obj;
  }
}

/**
 * The total number of related values
 * @member {Number} count
 */
RelatedResponseSchema.prototype.count = undefined;

/**
 * @member {Array.<module:model/RelatedResultResponse>} result
 */
RelatedResponseSchema.prototype.result = undefined;

