/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ReportScheduleRestApiGetReportRecipients model module.
 * @module model/ReportScheduleRestApiGetReportRecipients
 * @version v1
 */
export class ReportScheduleRestApiGetReportRecipients {
  /**
   * Constructs a new <code>ReportScheduleRestApiGetReportRecipients</code>.
   * @alias module:model/ReportScheduleRestApiGetReportRecipients
   * @class
   * @param type {String} 
   */
  constructor(type) {
    this.type = type;
  }

  /**
   * Constructs a <code>ReportScheduleRestApiGetReportRecipients</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReportScheduleRestApiGetReportRecipients} obj Optional instance to populate.
   * @return {module:model/ReportScheduleRestApiGetReportRecipients} The populated <code>ReportScheduleRestApiGetReportRecipients</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReportScheduleRestApiGetReportRecipients();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('recipient_config_json'))
        obj.recipientConfigJson = ApiClient.convertToType(data['recipient_config_json'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ReportScheduleRestApiGetReportRecipients.prototype.id = undefined;

/**
 * @member {String} recipientConfigJson
 */
ReportScheduleRestApiGetReportRecipients.prototype.recipientConfigJson = undefined;

/**
 * @member {String} type
 */
ReportScheduleRestApiGetReportRecipients.prototype.type = undefined;

