/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SavedQueryRestApiGetDatabase} from './SavedQueryRestApiGetDatabase';
import {SavedQueryRestApiGetUser} from './SavedQueryRestApiGetUser';

/**
 * The SavedQueryRestApiGet model module.
 * @module model/SavedQueryRestApiGet
 * @version v1
 */
export class SavedQueryRestApiGet {
  /**
   * Constructs a new <code>SavedQueryRestApiGet</code>.
   * @alias module:model/SavedQueryRestApiGet
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SavedQueryRestApiGet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SavedQueryRestApiGet} obj Optional instance to populate.
   * @return {module:model/SavedQueryRestApiGet} The populated <code>SavedQueryRestApiGet</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SavedQueryRestApiGet();
      if (data.hasOwnProperty('changed_on_delta_humanized'))
        obj.changedOnDeltaHumanized = ApiClient.convertToType(data['changed_on_delta_humanized'], Object);
      if (data.hasOwnProperty('created_by'))
        obj.createdBy = SavedQueryRestApiGetUser.constructFromObject(data['created_by']);
      if (data.hasOwnProperty('database'))
        obj.database = SavedQueryRestApiGetDatabase.constructFromObject(data['database']);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('schema'))
        obj.schema = ApiClient.convertToType(data['schema'], 'String');
      if (data.hasOwnProperty('sql'))
        obj.sql = ApiClient.convertToType(data['sql'], 'String');
      if (data.hasOwnProperty('sql_tables'))
        obj.sqlTables = ApiClient.convertToType(data['sql_tables'], Object);
      if (data.hasOwnProperty('template_parameters'))
        obj.templateParameters = ApiClient.convertToType(data['template_parameters'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Object} changedOnDeltaHumanized
 */
SavedQueryRestApiGet.prototype.changedOnDeltaHumanized = undefined;

/**
 * @member {module:model/SavedQueryRestApiGetUser} createdBy
 */
SavedQueryRestApiGet.prototype.createdBy = undefined;

/**
 * @member {module:model/SavedQueryRestApiGetDatabase} database
 */
SavedQueryRestApiGet.prototype.database = undefined;

/**
 * @member {String} description
 */
SavedQueryRestApiGet.prototype.description = undefined;

/**
 * @member {Number} id
 */
SavedQueryRestApiGet.prototype.id = undefined;

/**
 * @member {String} label
 */
SavedQueryRestApiGet.prototype.label = undefined;

/**
 * @member {String} schema
 */
SavedQueryRestApiGet.prototype.schema = undefined;

/**
 * @member {String} sql
 */
SavedQueryRestApiGet.prototype.sql = undefined;

/**
 * @member {Object} sqlTables
 */
SavedQueryRestApiGet.prototype.sqlTables = undefined;

/**
 * @member {String} templateParameters
 */
SavedQueryRestApiGet.prototype.templateParameters = undefined;

