/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Tables model module.
 * @module model/Tables
 * @version v1
 */
export class Tables {
  /**
   * Constructs a new <code>Tables</code>.
   * @alias module:model/Tables
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Tables</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tables} obj Optional instance to populate.
   * @return {module:model/Tables} The populated <code>Tables</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Tables();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('schema'))
        obj.schema = ApiClient.convertToType(data['schema'], 'String');
      if (data.hasOwnProperty('table_name'))
        obj.tableName = ApiClient.convertToType(data['table_name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Tables.prototype.id = undefined;

/**
 * @member {String} schema
 */
Tables.prototype.schema = undefined;

/**
 * @member {String} tableName
 */
Tables.prototype.tableName = undefined;

