/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ThumbnailQuerySchema model module.
 * @module model/ThumbnailQuerySchema
 * @version v1
 */
export class ThumbnailQuerySchema {
  /**
   * Constructs a new <code>ThumbnailQuerySchema</code>.
   * @alias module:model/ThumbnailQuerySchema
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ThumbnailQuerySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ThumbnailQuerySchema} obj Optional instance to populate.
   * @return {module:model/ThumbnailQuerySchema} The populated <code>ThumbnailQuerySchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ThumbnailQuerySchema();
      if (data.hasOwnProperty('force'))
        obj.force = ApiClient.convertToType(data['force'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} force
 */
ThumbnailQuerySchema.prototype.force = undefined;

