/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The User2 model module.
 * @module model/User2
 * @version v1
 */
export class User2 {
  /**
   * Constructs a new <code>User2</code>.
   * @alias module:model/User2
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>User2</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User2} obj Optional instance to populate.
   * @return {module:model/User2} The populated <code>User2</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new User2();
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} firstName
 */
User2.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
User2.prototype.lastName = undefined;

/**
 * @member {String} username
 */
User2.prototype.username = undefined;

