/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse20036 } from '../models';
import { InlineResponse400 } from '../models';
/**
 * DatasourcesApi - axios parameter creator
 * @export
 */
export const DatasourcesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get possible values for a datasource column
         * @param {string} datasourceType The type of datasource
         * @param {number} datasourceId The id of the datasource
         * @param {string} columnName The name of the column to get values for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1DatasourceDatasourceTypeDatasourceIdColumnColumnNameValuesGet: async (datasourceType: string, datasourceId: number, columnName: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'datasourceType' is not null or undefined
            if (datasourceType === null || datasourceType === undefined) {
                throw new RequiredError('datasourceType','Required parameter datasourceType was null or undefined when calling apiV1DatasourceDatasourceTypeDatasourceIdColumnColumnNameValuesGet.');
            }
            // verify required parameter 'datasourceId' is not null or undefined
            if (datasourceId === null || datasourceId === undefined) {
                throw new RequiredError('datasourceId','Required parameter datasourceId was null or undefined when calling apiV1DatasourceDatasourceTypeDatasourceIdColumnColumnNameValuesGet.');
            }
            // verify required parameter 'columnName' is not null or undefined
            if (columnName === null || columnName === undefined) {
                throw new RequiredError('columnName','Required parameter columnName was null or undefined when calling apiV1DatasourceDatasourceTypeDatasourceIdColumnColumnNameValuesGet.');
            }
            const localVarPath = `/api/v1/datasource/{datasource_type}/{datasource_id}/column/{column_name}/values/`
                .replace(`{${"datasource_type"}}`, encodeURIComponent(String(datasourceType)))
                .replace(`{${"datasource_id"}}`, encodeURIComponent(String(datasourceId)))
                .replace(`{${"column_name"}}`, encodeURIComponent(String(columnName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DatasourcesApi - functional programming interface
 * @export
 */
export const DatasourcesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get possible values for a datasource column
         * @param {string} datasourceType The type of datasource
         * @param {number} datasourceId The id of the datasource
         * @param {string} columnName The name of the column to get values for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1DatasourceDatasourceTypeDatasourceIdColumnColumnNameValuesGet(datasourceType: string, datasourceId: number, columnName: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20036>>> {
            const localVarAxiosArgs = await DatasourcesApiAxiosParamCreator(configuration).apiV1DatasourceDatasourceTypeDatasourceIdColumnColumnNameValuesGet(datasourceType, datasourceId, columnName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DatasourcesApi - factory interface
 * @export
 */
export const DatasourcesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get possible values for a datasource column
         * @param {string} datasourceType The type of datasource
         * @param {number} datasourceId The id of the datasource
         * @param {string} columnName The name of the column to get values for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1DatasourceDatasourceTypeDatasourceIdColumnColumnNameValuesGet(datasourceType: string, datasourceId: number, columnName: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20036>> {
            return DatasourcesApiFp(configuration).apiV1DatasourceDatasourceTypeDatasourceIdColumnColumnNameValuesGet(datasourceType, datasourceId, columnName, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DatasourcesApi - object-oriented interface
 * @export
 * @class DatasourcesApi
 * @extends {BaseAPI}
 */
export class DatasourcesApi extends BaseAPI {
    /**
     * 
     * @summary Get possible values for a datasource column
     * @param {string} datasourceType The type of datasource
     * @param {number} datasourceId The id of the datasource
     * @param {string} columnName The name of the column to get values for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DatasourcesApi
     */
    public async apiV1DatasourceDatasourceTypeDatasourceIdColumnColumnNameValuesGet(datasourceType: string, datasourceId: number, columnName: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20036>> {
        return DatasourcesApiFp(this.configuration).apiV1DatasourceDatasourceTypeDatasourceIdColumnColumnNameValuesGet(datasourceType, datasourceId, columnName, options).then((request) => request(this.axios, this.basePath));
    }
}
