/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Superset);
  }
}(this, function(expect, Superset) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ChartDataAsyncResponseSchema', function() {
      beforeEach(function() {
        instance = new Superset.ChartDataAsyncResponseSchema();
      });

      it('should create an instance of ChartDataAsyncResponseSchema', function() {
        // TODO: update the code to test ChartDataAsyncResponseSchema
        expect(instance).to.be.a(Superset.ChartDataAsyncResponseSchema);
      });

      it('should have the property channelId (base name: "channel_id")', function() {
        // TODO: update the code to test the property channelId
        expect(instance).to.have.property('channelId');
        // expect(instance.channelId).to.be(expectedValueLiteral);
      });

      it('should have the property jobId (base name: "job_id")', function() {
        // TODO: update the code to test the property jobId
        expect(instance).to.have.property('jobId');
        // expect(instance.jobId).to.be(expectedValueLiteral);
      });

      it('should have the property resultUrl (base name: "result_url")', function() {
        // TODO: update the code to test the property resultUrl
        expect(instance).to.have.property('resultUrl');
        // expect(instance.resultUrl).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property userId (base name: "user_id")', function() {
        // TODO: update the code to test the property userId
        expect(instance).to.have.property('userId');
        // expect(instance.userId).to.be(expectedValueLiteral);
      });

    });
  });

}));
