/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Superset);
  }
}(this, function(expect, Superset) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ChartDataSelectOptionsSchema', function() {
      beforeEach(function() {
        instance = new Superset.ChartDataSelectOptionsSchema();
      });

      it('should create an instance of ChartDataSelectOptionsSchema', function() {
        // TODO: update the code to test ChartDataSelectOptionsSchema
        expect(instance).to.be.a(Superset.ChartDataSelectOptionsSchema);
      });

      it('should have the property columns (base name: "columns")', function() {
        // TODO: update the code to test the property columns
        expect(instance).to.have.property('columns');
        // expect(instance.columns).to.be(expectedValueLiteral);
      });

      it('should have the property exclude (base name: "exclude")', function() {
        // TODO: update the code to test the property exclude
        expect(instance).to.have.property('exclude');
        // expect(instance.exclude).to.be(expectedValueLiteral);
      });

      it('should have the property rename (base name: "rename")', function() {
        // TODO: update the code to test the property rename
        expect(instance).to.have.property('rename');
        // expect(instance.rename).to.be(expectedValueLiteral);
      });

    });
  });

}));
