/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Superset);
  }
}(this, function(expect, Superset) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ScreenshotQuerySchema', function() {
      beforeEach(function() {
        instance = new Superset.ScreenshotQuerySchema();
      });

      it('should create an instance of ScreenshotQuerySchema', function() {
        // TODO: update the code to test ScreenshotQuerySchema
        expect(instance).to.be.a(Superset.ScreenshotQuerySchema);
      });

      it('should have the property force (base name: "force")', function() {
        // TODO: update the code to test the property force
        expect(instance).to.have.property('force');
        // expect(instance.force).to.be(expectedValueLiteral);
      });

      it('should have the property thumbSize (base name: "thumb_size")', function() {
        // TODO: update the code to test the property thumbSize
        expect(instance).to.have.property('thumbSize');
        // expect(instance.thumbSize).to.be(expectedValueLiteral);
      });

      it('should have the property windowSize (base name: "window_size")', function() {
        // TODO: update the code to test the property windowSize
        expect(instance).to.have.property('windowSize');
        // expect(instance.windowSize).to.be(expectedValueLiteral);
      });

    });
  });

}));
