/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Superset);
  }
}(this, function(expect, Superset) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ValidateSQLResponse', function() {
      beforeEach(function() {
        instance = new Superset.ValidateSQLResponse();
      });

      it('should create an instance of ValidateSQLResponse', function() {
        // TODO: update the code to test ValidateSQLResponse
        expect(instance).to.be.a(Superset.ValidateSQLResponse);
      });

      it('should have the property endColumn (base name: "end_column")', function() {
        // TODO: update the code to test the property endColumn
        expect(instance).to.have.property('endColumn');
        // expect(instance.endColumn).to.be(expectedValueLiteral);
      });

      it('should have the property lineNumber (base name: "line_number")', function() {
        // TODO: update the code to test the property lineNumber
        expect(instance).to.have.property('lineNumber');
        // expect(instance.lineNumber).to.be(expectedValueLiteral);
      });

      it('should have the property message (base name: "message")', function() {
        // TODO: update the code to test the property message
        expect(instance).to.have.property('message');
        // expect(instance.message).to.be(expectedValueLiteral);
      });

      it('should have the property startColumn (base name: "start_column")', function() {
        // TODO: update the code to test the property startColumn
        expect(instance).to.have.property('startColumn');
        // expect(instance.startColumn).to.be(expectedValueLiteral);
      });

    });
  });

}));
