/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Superset);
  }
}(this, function(expect, Superset) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ValidatorConfigJSON', function() {
      beforeEach(function() {
        instance = new Superset.ValidatorConfigJSON();
      });

      it('should create an instance of ValidatorConfigJSON', function() {
        // TODO: update the code to test ValidatorConfigJSON
        expect(instance).to.be.a(Superset.ValidatorConfigJSON);
      });

      it('should have the property op (base name: "op")', function() {
        // TODO: update the code to test the property op
        expect(instance).to.have.property('op');
        // expect(instance.op).to.be(expectedValueLiteral);
      });

      it('should have the property threshold (base name: "threshold")', function() {
        // TODO: update the code to test the property threshold
        expect(instance).to.have.property('threshold');
        // expect(instance.threshold).to.be(expectedValueLiteral);
      });

    });
  });

}));
