/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Superset);
  }
}(this, function(expect, Superset) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Superset.AdvancedDataTypeApi();
  });

  describe('(package)', function() {
    describe('AdvancedDataTypeApi', function() {
      describe('apiV1AdvancedDataTypeConvertGet', function() {
        it('should call apiV1AdvancedDataTypeConvertGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV1AdvancedDataTypeConvertGet call and complete the assertions
          /*
          var opts = {};

          instance.apiV1AdvancedDataTypeConvertGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Superset.AdvancedDataTypeSchema);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1AdvancedDataTypeTypesGet', function() {
        it('should call apiV1AdvancedDataTypeTypesGet successfully', function(done) {
          // TODO: uncomment apiV1AdvancedDataTypeTypesGet call and complete the assertions
          /*

          instance.apiV1AdvancedDataTypeTypesGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Superset.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
