/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Superset);
  }
}(this, function(expect, Superset) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Superset.SecurityApi();
  });

  describe('(package)', function() {
    describe('SecurityApi', function() {
      describe('apiV1SecurityCsrfTokenGet', function() {
        it('should call apiV1SecurityCsrfTokenGet successfully', function(done) {
          // TODO: uncomment apiV1SecurityCsrfTokenGet call and complete the assertions
          /*

          instance.apiV1SecurityCsrfTokenGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Superset.InlineResponse20045);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1SecurityGuestTokenPost', function() {
        it('should call apiV1SecurityGuestTokenPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV1SecurityGuestTokenPost call and complete the assertions
          /*

          instance.apiV1SecurityGuestTokenPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Superset.InlineResponse20059);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1SecurityLoginPost', function() {
        it('should call apiV1SecurityLoginPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV1SecurityLoginPost call and complete the assertions
          /*

          instance.apiV1SecurityLoginPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Superset.InlineResponse20060);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1SecurityRefreshPost', function() {
        it('should call apiV1SecurityRefreshPost successfully', function(done) {
          // TODO: uncomment apiV1SecurityRefreshPost call and complete the assertions
          /*

          instance.apiV1SecurityRefreshPost(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Superset.InlineResponse20061);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
