/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ChartDataSelectOptionsSchema
 */
export interface ChartDataSelectOptionsSchema {
    /**
     * Columns which to select from the input data, in the desired order. If columns are renamed, the original column name should be referenced here.
     * @type {Array<string>}
     * @memberof ChartDataSelectOptionsSchema
     */
    columns?: Array<string>;
    /**
     * Columns to exclude from selection.
     * @type {Array<string>}
     * @memberof ChartDataSelectOptionsSchema
     */
    exclude?: Array<string>;
    /**
     * columns which to rename, mapping source column to target column. For instance, `{'y': 'y2'}` will rename the column `y` to `y2`.
     * @type {Array<any>}
     * @memberof ChartDataSelectOptionsSchema
     */
    rename?: Array<any>;
}
