/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ChartRestApiGetListSqlaTable
 */
export interface ChartRestApiGetListSqlaTable {
    /**
     * 
     * @type {string}
     * @memberof ChartRestApiGetListSqlaTable
     */
    defaultEndpoint?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChartRestApiGetListSqlaTable
     */
    tableName: string;
}
