/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChartDataDatasource } from './chart-data-datasource';
import { ChartDataQueryObject } from './chart-data-query-object';
/**
 * 
 * @export
 * @interface ChartDataQueryContextSchema
 */
export interface ChartDataQueryContextSchema {
    /**
     * Override the default cache timeout
     * @type {number}
     * @memberof ChartDataQueryContextSchema
     */
    customCacheTimeout?: number | null;
    /**
     * 
     * @type {ChartDataDatasource}
     * @memberof ChartDataQueryContextSchema
     */
    datasource?: ChartDataDatasource;
    /**
     * Should the queries be forced to load from the source. Default: `false`
     * @type {boolean}
     * @memberof ChartDataQueryContextSchema
     */
    force?: boolean | null;
    /**
     * 
     * @type {any}
     * @memberof ChartDataQueryContextSchema
     */
    formData?: any | null;
    /**
     * 
     * @type {Array<ChartDataQueryObject>}
     * @memberof ChartDataQueryContextSchema
     */
    queries?: Array<ChartDataQueryObject>;
    /**
     * 
     * @type {any}
     * @memberof ChartDataQueryContextSchema
     */
    resultFormat?: any;
    /**
     * 
     * @type {any}
     * @memberof ChartDataQueryContextSchema
     */
    resultType?: any;
}
