/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ChartDataPivotOptionsSchema
 */
export interface ChartDataPivotOptionsSchema {
    /**
     * The keys are the name of the aggregate column to be created, and the values specify the details of how to apply the aggregation. If an operator requires additional options, these can be passed here to be unpacked in the operator call. The following numpy operators are supported: average, argmin, argmax, cumsum, cumprod, max, mean, median, nansum, nanmin, nanmax, nanmean, nanmedian, min, percentile, prod, product, std, sum, var. Any options required by the operator can be passed to the `options` object.  In the example, a new column `first_quantile` is created based on values in the column `my_col` using the `percentile` operator with the `q=0.25` parameter.
     * @type {any}
     * @memberof ChartDataPivotOptionsSchema
     */
    aggregates?: any;
    /**
     * Value to replace missing pivot columns names with.
     * @type {string}
     * @memberof ChartDataPivotOptionsSchema
     */
    columnFillValue?: string;
    /**
     * Columns to group by on the table columns
     * @type {Array<string>}
     * @memberof ChartDataPivotOptionsSchema
     */
    columns?: Array<string>;
    /**
     * Do not include columns whose entries are all missing (default: `true`).
     * @type {boolean}
     * @memberof ChartDataPivotOptionsSchema
     */
    dropMissingColumns?: boolean;
    /**
     * Name of marginal distribution row/column. (default: `All`)
     * @type {string}
     * @memberof ChartDataPivotOptionsSchema
     */
    marginalDistributionName?: string;
    /**
     * Add totals for row/column. (default: `false`)
     * @type {boolean}
     * @memberof ChartDataPivotOptionsSchema
     */
    marginalDistributions?: boolean;
    /**
     * Value to replace missing values with in aggregate calculations.
     * @type {number}
     * @memberof ChartDataPivotOptionsSchema
     */
    metricFillValue?: number;
}
