/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DashboardRestApiGetListUser
 */
export interface DashboardRestApiGetListUser {
    /**
     * 
     * @type {string}
     * @memberof DashboardRestApiGetListUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardRestApiGetListUser
     */
    firstName: string;
    /**
     * 
     * @type {number}
     * @memberof DashboardRestApiGetListUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DashboardRestApiGetListUser
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardRestApiGetListUser
     */
    username: string;
}
