/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse2002FiltersColumnName } from './inline-response2002-filters-column-name';
/**
 * 
 * @export
 * @interface InlineResponse2002Filters
 */
export interface InlineResponse2002Filters {
    /**
     * 
     * @type {Array<InlineResponse2002FiltersColumnName>}
     * @memberof InlineResponse2002Filters
     */
    columnName?: Array<InlineResponse2002FiltersColumnName>;
}
