/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CssTemplateRestApiGet } from './css-template-rest-api-get';
import { InlineResponse2001DescriptionColumns } from './inline-response2001-description-columns';
import { InlineResponse2001LabelColumns } from './inline-response2001-label-columns';
/**
 * 
 * @export
 * @interface InlineResponse20014
 */
export interface InlineResponse20014 {
    /**
     * 
     * @type {InlineResponse2001DescriptionColumns}
     * @memberof InlineResponse20014
     */
    descriptionColumns?: InlineResponse2001DescriptionColumns;
    /**
     * The item id
     * @type {string}
     * @memberof InlineResponse20014
     */
    id?: string;
    /**
     * 
     * @type {InlineResponse2001LabelColumns}
     * @memberof InlineResponse20014
     */
    labelColumns?: InlineResponse2001LabelColumns;
    /**
     * 
     * @type {CssTemplateRestApiGet}
     * @memberof InlineResponse20014
     */
    result?: CssTemplateRestApiGet;
    /**
     * A list of columns
     * @type {Array<string>}
     * @memberof InlineResponse20014
     */
    showColumns?: Array<string>;
    /**
     * A title to render. Will be translated by babel
     * @type {string}
     * @memberof InlineResponse20014
     */
    showTitle?: string;
}
