/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChartRestApiPost } from './chart-rest-api-post';
/**
 * 
 * @export
 * @interface InlineResponse2012
 */
export interface InlineResponse2012 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2012
     */
    id?: number;
    /**
     * 
     * @type {ChartRestApiPost}
     * @memberof InlineResponse2012
     */
    result?: ChartRestApiPost;
}
