/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TagRestApiPost } from './tag-rest-api-post';
/**
 * 
 * @export
 * @interface InlineResponse20115
 */
export interface InlineResponse20115 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20115
     */
    id?: string;
    /**
     * 
     * @type {TagRestApiPost}
     * @memberof InlineResponse20115
     */
    result?: TagRestApiPost;
}
