/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TableMetadataColumnsResponse } from './table-metadata-columns-response';
import { TableMetadataForeignKeysIndexesResponse } from './table-metadata-foreign-keys-indexes-response';
import { TableMetadataPrimaryKeyResponse } from './table-metadata-primary-key-response';
/**
 * 
 * @export
 * @interface TableMetadataResponseSchema
 */
export interface TableMetadataResponseSchema {
    /**
     * A list of columns and their metadata
     * @type {Array<TableMetadataColumnsResponse>}
     * @memberof TableMetadataResponseSchema
     */
    columns?: Array<TableMetadataColumnsResponse>;
    /**
     * A list of foreign keys and their metadata
     * @type {Array<TableMetadataForeignKeysIndexesResponse>}
     * @memberof TableMetadataResponseSchema
     */
    foreignKeys?: Array<TableMetadataForeignKeysIndexesResponse>;
    /**
     * A list of indexes and their metadata
     * @type {Array<TableMetadataForeignKeysIndexesResponse>}
     * @memberof TableMetadataResponseSchema
     */
    indexes?: Array<TableMetadataForeignKeysIndexesResponse>;
    /**
     * The name of the table
     * @type {string}
     * @memberof TableMetadataResponseSchema
     */
    name?: string;
    /**
     * Primary keys metadata
     * @type {TableMetadataPrimaryKeyResponse}
     * @memberof TableMetadataResponseSchema
     */
    primaryKey?: TableMetadataPrimaryKeyResponse;
    /**
     * SQL select star
     * @type {string}
     * @memberof TableMetadataResponseSchema
     */
    selectStar?: string;
}
