/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TableMetadataOptionsResponse
 */
export interface TableMetadataOptionsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof TableMetadataOptionsResponse
     */
    deferrable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TableMetadataOptionsResponse
     */
    initially?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TableMetadataOptionsResponse
     */
    match?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TableMetadataOptionsResponse
     */
    ondelete?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TableMetadataOptionsResponse
     */
    onupdate?: boolean;
}
