/* tslint:disable */
/* eslint-disable */
/**
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TemporaryCachePostSchema
 */
export interface TemporaryCachePostSchema {
    /**
     * Any type of JSON supported text.
     * @type {string}
     * @memberof TemporaryCachePostSchema
     */
    value: string;
}
